-- This script runs once, against the database specified by POSTGRES_DB
-- (custodian_db) when the Postgres data directory is first initialized.
--
-- The database (custodian_db) and the role (custodian_user) are already
-- created automatically by the postgres image from the POSTGRES_DB,
-- POSTGRES_USER, and POSTGRES_PASSWORD environment variables in
-- docker-compose.yml, so we do NOT recreate them here.
--
-- Add any extensions or one-time bootstrap SQL below, e.g.:
--   CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
