"""empty message

Revision ID: 230f64d68d55
Revises: e9974de096a8
Create Date: 2026-03-23 02:17:25.441608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '230f64d68d55'
down_revision: Union[str, None] = 'e9974de096a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_custodians_email', table_name='custodians')
    op.drop_index('ix_custodians_employee_id', table_name='custodians')
    op.drop_index('ix_custodians_id', table_name='custodians')
    op.drop_table('custodians')
    op.add_column('j3', sa.Column('groupnum', sa.Integer(), nullable=False))
    op.add_column('j3', sa.Column('hire_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_j3_groupnum'), 'j3', ['groupnum'], unique=False)
    op.drop_constraint('tasks_assigned_to_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_assigned_to_fkey', 'tasks', 'j3', ['assigned_to'], ['id'])
    op.drop_index(op.f('ix_j3_groupnum'), table_name='j3')
    op.drop_column('j3', 'hire_date')
    op.drop_column('j3', 'groupnum')
    op.create_table('custodians',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hire_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='custodians_pkey')
    )
    op.create_index('ix_custodians_id', 'custodians', ['id'], unique=False)
    op.create_index('ix_custodians_employee_id', 'custodians', ['employee_id'], unique=False)
    op.create_index('ix_custodians_email', 'custodians', ['email'], unique=False)
    # ### end Alembic commands ###
