"""empty message

Revision ID: 38908afbba78
Revises: 4e20d35eda22
Create Date: 2026-03-29 01:43:51.122640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38908afbba78'
down_revision: Union[str, None] = '4e20d35eda22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('j2', sa.Column('groupnum', sa.Integer(), nullable=False))
    op.add_column('j2', sa.Column('hire_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True))
    op.create_index(op.f('ix_j2_groupnum'), 'j2', ['groupnum'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_j2_groupnum'), table_name='j2')
    op.drop_column('j2', 'hire_date')
    op.drop_column('j2', 'groupnum')
    # ### end Alembic commands ###
