"""empty message

Revision ID: 7b6c3da95734
Revises: 
Create Date: 2026-01-04 05:27:10.781157

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import Column, String, Integer, Text, Boolean, DateTime, Enum, ForeignKey
from sqlalchemy.sql import func
from models import TaskStatus

# revision identifiers, used by Alembic.
revision: str = '7b6c3da95734'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'buildings',
        Column('id', Integer, primary_key=True, index=True),
        Column('name', String(200), nullable=False),
        Column('address', String(500), nullable=False),
        Column('building_code', String(20), unique=True, index=True),
        Column('floors', Integer),
        Column('description', Text),
        Column('is_active', Boolean, default=True),
        Column('created_at', DateTime(timezone=True), server_default=func.now()),
        Column('updated_at', DateTime(timezone=True), onupdate=func.now())
    )
    
    op.create_table(
        'custodians',
        Column('id', Integer, primary_key=True, index=True),
        Column('first_name', String(100), nullable=False),
        Column('last_name', String(100), nullable=False),
        Column('email', String(255), unique=True, index=True, nullable=False),
        Column('phone', String(20)),
        Column('employee_id', String(50), unique=True, index=True),
        Column('is_active', Boolean, default=True),
        Column('hire_date', DateTime(timezone=True), server_default=func.now()),
        Column('created_at', DateTime(timezone=True), server_default=func.now()),
        Column('updated_at', DateTime(timezone=True), onupdate=func.now())
    )
    op.create_table(
        'supervisors',
        Column('id', Integer, primary_key=True, index=True),
        Column('name', String(100), nullable=False)
    )
    op.create_table(
        'j3',
        Column('id', Integer, primary_key=True, index=True),
        Column('name', String(100), nullable=False),
        Column('supervisor_id', ForeignKey('supervisors.id'))
    )
    op.create_table(
        'tasks',
        Column('id', Integer, primary_key=True,index=True),
        Column('title', String(200), nullable=False),
        Column('description', Text),
        Column('priority', String(20), default="medium"),
        Column('assigned_to', Integer, ForeignKey('custodians.id')),
        Column('building_id', Integer, ForeignKey('buildings.id')),
        Column('scheduled_date', DateTime(timezone=True)),
        Column('completed_date', DateTime(timezone=True)),
        Column('created_at', DateTime(timezone=True), server_default=func.now()),
        Column('updated_at', DateTime(timezone=True), onupdate=func.now()), 
        Column('status', Enum(TaskStatus), default=TaskStatus.pending)

    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buildings')
    op.drop_table('custodians')
    op.drop_table('j3')
    op.drop_table('supervisors')
    op.drop_table('tasks')
    # ### end Alembic commands ###
